/*
 * Launa Bucher-Austin
 * May 05 2020
 * This program will allow the user to convert vrobits into various other forms of alien currency. 
 */

/**
 *
 * @author launa
 */
public class Vrobitsfrm extends javax.swing.JFrame {

    /**
     * Creates new form Vrobitsfrm
     */
    public Vrobitsfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vrobitlbl = new javax.swing.JLabel();
        ttllbl = new javax.swing.JLabel();
        vrobittxt = new javax.swing.JTextField();
        drobzitlbl = new javax.swing.JLabel();
        clickwickslbl = new javax.swing.JLabel();
        gazoontightlbl = new javax.swing.JLabel();
        frazointlbl = new javax.swing.JLabel();
        blointointslbl = new javax.swing.JLabel();
        drobzittxt = new javax.swing.JTextField();
        clickwicktxt = new javax.swing.JTextField();
        gazoontighttxt = new javax.swing.JTextField();
        frazointtxt = new javax.swing.JTextField();
        blointointtxt = new javax.swing.JTextField();
        remainlbld = new javax.swing.JLabel();
        remaintxtd = new javax.swing.JTextField();
        calculatebtn = new javax.swing.JButton();
        remainlblc = new javax.swing.JLabel();
        remainlblg = new javax.swing.JLabel();
        remainlblf = new javax.swing.JLabel();
        remainlblb = new javax.swing.JLabel();
        remaintxtc = new javax.swing.JTextField();
        remaintxtg = new javax.swing.JTextField();
        remaintxtf = new javax.swing.JTextField();
        remaintxtb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vrobitlbl.setText("Please enter the number of vrobits : ");

        ttllbl.setText("Zirboin Financial");

        vrobittxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrobittxtActionPerformed(evt);
            }
        });

        drobzitlbl.setText("Drobzits : ");

        clickwickslbl.setText("Clickwicks : ");

        gazoontightlbl.setText("Gazoontights : ");

        frazointlbl.setText("Frazoints : ");

        blointointslbl.setText("Blointoints : ");

        remainlbld.setText("Remaining vrobits : ");

        calculatebtn.setText("Calculate");
        calculatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebtnActionPerformed(evt);
            }
        });

        remainlblc.setText("Remaining vrobits : ");

        remainlblg.setText("Remaining vrobits :");

        remainlblf.setText("Remaining vrobits :");

        remainlblb.setText("Remaining vrobits :");

        remaintxtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remaintxtcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(ttllbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vrobitlbl)
                                .addGap(43, 43, 43)
                                .addComponent(vrobittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(calculatebtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(drobzitlbl)
                                            .addComponent(clickwickslbl))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clickwicktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                            .addComponent(drobzittxt)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gazoontightlbl)
                                            .addComponent(frazointlbl)
                                            .addComponent(blointointslbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(frazointtxt)
                                            .addComponent(gazoontighttxt)
                                            .addComponent(blointointtxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(remainlbld)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(remaintxtd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(remainlblg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(remaintxtg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(remainlblf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(remaintxtf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(remainlblb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(remaintxtb))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(remainlblc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(remaintxtc)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ttllbl)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrobitlbl)
                    .addComponent(vrobittxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculatebtn))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drobzitlbl)
                    .addComponent(drobzittxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainlbld)
                    .addComponent(remaintxtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clickwickslbl)
                    .addComponent(clickwicktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainlblc)
                    .addComponent(remaintxtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gazoontightlbl)
                    .addComponent(gazoontighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainlblg)
                    .addComponent(remaintxtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frazointlbl)
                    .addComponent(frazointtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainlblf)
                    .addComponent(remaintxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blointointslbl)
                    .addComponent(blointointtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainlblb)
                    .addComponent(remaintxtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vrobittxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrobittxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vrobittxtActionPerformed

    private void calculatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebtnActionPerformed
      int vrotot, vroremaind, vroremainc, vroremaing, vroremainf, vroremainb, drobzit, clickwick, gazoontight, frazoint, blointoint;
      
      vrotot = Integer.parseInt(vrobittxt.getText());
      
     drobzit = vrotot/100000;
     vroremaind = vrotot % 1000000;
     clickwick = vrotot/50000;
     vroremainc = vrotot % 50000;
     gazoontight = vrotot/10000;
     vroremaing = vrotot % 10000;
     frazoint = vrotot/1000;
     vroremainf = vrotot % 1000;
     blointoint = vrotot/500;
     vroremainb = vrotot % 500;
     
     drobzittxt.setText(String.valueOf(drobzit));
     clickwicktxt.setText(String.valueOf(clickwick));
     gazoontighttxt.setText(String.valueOf(gazoontight));
     frazointtxt.setText(String.valueOf(frazoint));
     blointointtxt.setText(String.valueOf(blointoint));
     
     remaintxtd.setText(String.valueOf(vroremaind));
     remaintxtc.setText(String.valueOf(vroremainc));
     remaintxtg.setText(String.valueOf(vroremaing));
     remaintxtf.setText(String.valueOf(vroremaing));
     remaintxtb.setText(String.valueOf(vroremainb));
     
      
              
    }//GEN-LAST:event_calculatebtnActionPerformed

    private void remaintxtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remaintxtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remaintxtcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vrobitsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vrobitsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vrobitsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vrobitsfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vrobitsfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blointointslbl;
    private javax.swing.JTextField blointointtxt;
    private javax.swing.JButton calculatebtn;
    private javax.swing.JLabel clickwickslbl;
    private javax.swing.JTextField clickwicktxt;
    private javax.swing.JLabel drobzitlbl;
    private javax.swing.JTextField drobzittxt;
    private javax.swing.JLabel frazointlbl;
    private javax.swing.JTextField frazointtxt;
    private javax.swing.JLabel gazoontightlbl;
    private javax.swing.JTextField gazoontighttxt;
    private javax.swing.JLabel remainlblb;
    private javax.swing.JLabel remainlblc;
    private javax.swing.JLabel remainlbld;
    private javax.swing.JLabel remainlblf;
    private javax.swing.JLabel remainlblg;
    private javax.swing.JTextField remaintxtb;
    private javax.swing.JTextField remaintxtc;
    private javax.swing.JTextField remaintxtd;
    private javax.swing.JTextField remaintxtf;
    private javax.swing.JTextField remaintxtg;
    private javax.swing.JLabel ttllbl;
    private javax.swing.JLabel vrobitlbl;
    private javax.swing.JTextField vrobittxt;
    // End of variables declaration//GEN-END:variables
}
